---
fields:
  batched:
    - name: Face Shield Frame
      openproject_key: customField7
      batch_size: 10
    - name: Visors
      openproject_key: customField8
      batch_size: 10
    - name: Ear Savers
      openproject_key: customField9
      batch_size: 10

server:
  port: 80

openProject:
  url: https://track.qa.bcc3d.ca
  password: sp45SG0m6y0B
  username: bot@track.bcc3d.ca
